// svelte-todo/src/TaskDetails.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export let selectedTask;

  const dispatch = createEventDispatcher();

    // Variables locales para descripción y fecha
  let description = '';
  let date = '';

  // Si hay una tarea seleccionada, inicializa los campos
  $: if (selectedTask) {
    const task = selectedTask.detail;
    description = task.description;
    date = task.date;
  }
 
  const updateTask = () => {   
    dispatch('updateTask', { ...selectedTask.detail, description, date });
  };
</script>

{#if selectedTask}

  <div class="task-details">    
    <h2>Task Details</h2>
    <div>
      <label>Description:</label>
      <input
        type="text"
        bind:value={description}
        on:input={updateTask}
      />
    </div>
    <div>
      <label>Date:</label>
      <input
        type="date"
        bind:value={date}
        on:input={updateTask}
      />
    </div>
  </div>
{:else}
  <div class="task-details">Select a task to see details</div>
{/if}

// react-todo/src/TaskDetails.js
import React from 'react';

const TaskDetails = ({ task, onUpdateTask }) => {
  if (!task) {
    return <div className="task-details">Select a task to see details</div>;
  }

  const handleDescriptionChange = (e) => {
    const updatedTask = { ...task, description: e.target.value };
    onUpdateTask(updatedTask);
  };

  const handleDateChange = (e) => {
    const updatedTask = { ...task, date: e.target.value };
    onUpdateTask(updatedTask);
  };

  return (
    <div className="task-details">
      <h2>Task Details</h2>
      <div>
        <label>Description:</label>
        <input
          type="text"
          value={task.description}
          onChange={handleDescriptionChange}
        />
      </div>
      <div>
        <label>Date:</label>
        <input
          type="date"
          value={task.date}
          onChange={handleDateChange}
        />
      </div>
    </div>
  );
};

export default TaskDetails;
