// svelte-todo/src/TaskList.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export let tasks;
  const dispatch = createEventDispatcher();

  const selectTask = (task) => {
    dispatch('selectTask', task);
  };
</script>

<div class="task-list">
  <h2>Tasks</h2>
  <ul>
    {#each $tasks as task}
      <li on:click={() => selectTask(task)}>
        {task.description}
      </li>
    {/each}
  </ul>
</div>

// react-todo/src/TaskList.js
import React from 'react';

const TaskList = ({ tasks, onSelectTask }) => {
  return (
    <div className="task-list">
      <h2>Tasks</h2>
      <ul>
        {tasks.map(task => (
          <li key={task.id} onClick={() => onSelectTask(task.id)}>
            {task.description}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default TaskList;
