// react-todo/src/TaskList.js
import React from 'react';

const TaskList = ({ tasks, onSelectTask }) => {
  return (
    <div className="task-list">
      <h2>Tasks</h2>
      <ul>
        {tasks.map(task => (
          <li key={task.id} onClick={() => onSelectTask(task.id)}>
            {task.description}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default TaskList;

// vue-todo/src/components/TaskList.vue
<template>
  <div class="task-list">
    <h2>Tasks</h2>
    <ul>
      <li v-for="task in tasks" :key="task.id" @click="selectTask(task.id)">
        {{ task.description }}
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'TaskList',
  props: {
    tasks: Array,
  },
  methods: {
    selectTask(taskId) {
      this.$emit('selectTask', taskId);
    },
  },
};
</script>
