// react-todo/src/TaskDetails.js
import React from 'react';

const TaskDetails = ({ task, onUpdateTask }) => {
  if (!task) {
    return <div className="task-details">Select a task to see details</div>;
  }

  const handleDescriptionChange = (e) => {
    const updatedTask = { ...task, description: e.target.value };
    onUpdateTask(updatedTask);
  };

  const handleDateChange = (e) => {
    const updatedTask = { ...task, date: e.target.value };
    onUpdateTask(updatedTask);
  };

  return (
    <div className="task-details">
      <h2>Task Details</h2>
      <div>
        <label>Description:</label>
        <input
          type="text"
          value={task.description}
          onChange={handleDescriptionChange}
        />
      </div>
      <div>
        <label>Date:</label>
        <input
          type="date"
          value={task.date}
          onChange={handleDateChange}
        />
      </div>
    </div>
  );
};

export default TaskDetails;

// vue-todo/src/components/TaskDetails.vue
<template>
  <div class="task-details">
    <h2>Task Details</h2>
    <div v-if="task">
      <div>
        <label>Description:</label>
        <input type="text" v-model="localTask.description" @input="updateTask" />
      </div>
      <div>
        <label>Date:</label>
        <input type="date" v-model="localTask.date" @input="updateTask" />
      </div>
    </div>
    <div v-else>Select a task to see details</div>
  </div>
</template>

<script>
import { reactive, watch } from 'vue';

export default {
  name: 'TaskDetails',
  props: {
    task: Object,
  },
  setup(props, { emit }) {
    const localTask = reactive({ ...props.task });

    watch(() => props.task, (newTask) => {
      Object.assign(localTask, newTask);
    });

    const updateTask = () => {
      emit('updateTask', { ...localTask });
    };

    return {
      localTask,
      updateTask,
    };
  },
};
</script>
