// react-todo/src/App.js
import React, { useState } from 'react';
import TaskList from './TaskList';
import TaskDetails from './TaskDetails';
import './App.css';

const App = () => {
  const [tasks, setTasks] = useState([
    { id: 1, description: 'Task 1', date: '2024-06-14' },
    { id: 2, description: 'Task 2', date: '2024-06-15' }
  ]);

  const [selectedTaskId, setSelectedTaskId] = useState(null);

  const selectTask = (taskId) => {
    setSelectedTaskId(taskId);
  };

  const updateTask = (updatedTask) => {
    setTasks(tasks.map(task => task.id === updatedTask.id ? updatedTask : task));
  };

  const selectedTask = tasks.find(task => task.id === selectedTaskId);

  return (
    <div className="app">
      <TaskList tasks={tasks} onSelectTask={selectTask} />
      <TaskDetails task={selectedTask} onUpdateTask={updateTask} />
    </div>
  );
};

export default App;

// svelte-todo/src/App.svelte
<script>
  import { writable } from 'svelte/store';
  import TaskList from './TaskList.svelte';
  import TaskDetails from './TaskDetails.svelte';

  const tasks = writable([
    { id: 1, description: 'Task 1', date: '2024-06-14' },
    { id: 2, description: 'Task 2', date: '2024-06-15' }
  ]);

  let selectedTask = null;

  const selectTask = (task) => {
    selectedTask = task;
  };

  const updateTask = (updatedTask) => {
    tasks.update(ts =>
      ts.map(task => task.id === updatedTask.detail.id ? updatedTask.detail : task)
    );
    selectedTask = updatedTask;
  };
</script>


<div class="app">
  <TaskList {tasks} on:selectTask={selectTask} />
  <TaskDetails {selectedTask} on:updateTask={updateTask} />
</div>
